### ISSUE TITLE
earnings data is showing abnormal of  xstella  

### ISSUE THREAD

**Issue by wenhandi** [stellaswap/core#3]
Hello, I am one of your users.
xstella The earnings data is showing abnormal, a screenshot showing the abnormality is as follows.
![ea11b881c9de5b9e6ab0e21f28dc560](https://user-images.githubusercontent.com/12582497/167301726-9c0767ef-e88d-4828-a65f-82ac968774a8.jpg)

Earnings are now showing normally after being collected
[Transaction details](https://moonscan.io//tx/0x8d870797ab33f962d4df107cd2a406e5fb009a71047dab91d561dcf115ecf72d)
Please fix the bug and I would like to know if I have lost my earnings

Looking forward to your reply

**Comment by atticuzor** [comment]
Please take this to discord.stellaswap.com
